export interface OptionData {
  StockName: string;
  OptionName: string;
  ExpiryDate: string;
  FinancialReport?: string;
  'X-Day'?: string | null;
  Premium: number;
  PoW_Simulation_Mean_Earnings?: number;
  '100k_Invested_Loss_Mean'?: number;
  '1_2_3_ProbOfWorthless_Weighted': number;
  ProbWorthless_Bayesian_IsoCal: number;
  '1_ProbOfWorthless_Original': number;
  '2_ProbOfWorthless_Calibrated': number;
  '3_ProbOfWorthless_Historical_IV': number;
  Lower_Bound_at_Accuracy: number;
  LossAtBadDecline: number;
  LossAtWorstDecline: number;
  PoW_Stats_MedianLossPct: number;
  PoW_Stats_WorstLossPct: number;
  PoW_Stats_MedianLoss: number;
  PoW_Stats_WorstLoss: number;
  PoW_Stats_MedianProbOfWorthless: number;
  PoW_Stats_MinProbOfWorthless: number;
  PoW_Stats_MaxProbOfWorthless: number;
  LossAt100DayWorstDecline: number;
  LossAt_2008_100DayWorstDecline: number;
  Mean_Accuracy: number;
  Lower_Bound_HistMedianIV_at_Accuracy: number;
  Lower_Bound: number;
  Lower_Bound_HistMedianIV: number;
  Bid_Ask_Mid_Price: number;
  Option_Price_Min: number;
  NumberOfContractsBasedOnLimit: number;
  Bid: number;
  ProfitLossPctLeastBad: number;
  Loss_Least_Bad: number;
  IV_AllMedianIV_Maximum100DaysToExp_Ratio: number;
  StockPrice: number;
  DaysToExpiry: number;
  AskBidSpread: number;
  Underlying_Value: number;
  StrikePrice: number;
  StockPrice_After_2008_100DayWorstDecline: number;
  LossAt50DayWorstDecline: number;
  LossAt_2008_50DayWorstDecline: number;
  ProfitLossPctBad: number;
  ProfitLossPctWorst: number;
  ProfitLossPct100DayWorst: number;
  ImpliedVolatility: number;
  TodayStockMedianIV_Maximum100DaysToExp: number;
  AllMedianIV_Maximum100DaysToExp: number;
  ExpiryDate_Lower_Bound_Minus_Pct_Based_on_Accuracy: number;
  StrikeBelowLowerAtAcc?: string;
  Ask?: number;
  WorstHistoricalDecline?: number;
  BadHistoricalDecline?: number;
  ImpliedVolatilityUntilExpiry?: number;
  StockPrice_After_100DayWorstDecline?: number;
  StockPrice_After_50DayWorstDecline?: number;
  StockPrice_After_2008_50DayWorstDecline?: number;
  '100DayMaxPrice'?: number;
  '100DayMaxPriceDate'?: string;
  '50DayMaxPrice'?: number;
  '50DayMaxPriceDate'?: string;
  Historical100DaysWorstDecline?: number;
  Historical50DaysWorstDecline?: number;
  '2008_100DaysWorstDecline'?: number;
  '2008_50DaysWorstDecline'?: number;
  // IV Data fields
  IV_ClosestToStrike?: number;
  IV_UntilExpiryClosestToStrike?: number;
  LowerBoundClosestToStrike?: number;
  LowerBoundDistanceFromCurrentPrice?: number;
  LowerBoundDistanceFromStrike?: number;
  ImpliedDownPct?: number;
  ToStrikePct?: number;
  SafetyMultiple?: number;
  SigmasToStrike?: number;
  ProbAssignment?: number;
  SafetyCategory?: string;
  CushionMinusIVPct?: number;
  // Calculated field
  PotentialLossAtLowerBound?: number | null;
}

export interface OptionsFilter {
  stockName?: string;
  minPremium?: number;
  maxPremium?: number;
  minDaysToExpiry?: number;
  maxDaysToExpiry?: number;
  minProbOfWorthless?: number;
  maxProbOfWorthless?: number;
}