// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isaojcmuooftwhdnubhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzYW9qY211b29mdHdoZG51YmhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjE4MTgsImV4cCI6MjA3MDM5NzgxOH0.cexAMM2q1sLCAIpRUe2L-NUhKFV5RUVaT2tR8nt-PjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});